# Generated by Django 3.1.14 on 2023-12-27 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='place',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
